import { NextResponse } from 'next/server'

export async function POST(req: Request) {
  const body = await req.json().catch(() => ({}))
  const prompt = typeof body.prompt === 'string' ? body.prompt : ''

  // Minimal mock AI agent response: returns an action JSON list
  const actions = [
    {
      type: 'writeFile',
      path: '/src/App.tsx',
      content: `export default function App(){ return (<div>Generated by Dozer AI for prompt: ${prompt}</div>) }`
    }
  ]

  return NextResponse.json({ ok: true, actions })
}

export async function GET() {
  return NextResponse.json({ ok: true, status: 'agent ready' })
}
