import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}))
  const prompt = typeof body.prompt === 'string' ? body.prompt : ''

  const actions = [
    {
      type: 'writeFile',
      path: '/src/App.tsx',
      content: `export default function App(){ return (<div>Generated by Dozer AI for prompt: ${prompt}</div>) }`,
    },
  ]

  const action = {
    type: 'message',
    text: `受信: ${prompt.slice(0, 200)}${prompt.length > 200 ? '…' : ''}`,
  }

  return NextResponse.json({ ok: true, action, actions })
}

export async function GET() {
  return NextResponse.json({ ok: true, status: 'agent ready' })
}
